[aes_ctr]
title = AES CTR String encrypting and decrypting
group = Runtime
help = Settings for KEY GENERATION when using the seed commands. The salt values must be between 0 and 255. ** ONCE SET THESES SHOULD NOT BE ALTERED AS IT WILL MEAN ANYTHING PREVIOUSLY ENCODED WILL NOT WORK **

salt_01.type = integer
salt_01.default = 88

salt_02.type = integer
salt_02.default = 154

salt_03.type = integer
salt_03.default = 44

salt_04.type = integer
salt_04.default = 241

salt_05.type = integer
salt_05.default = 126

salt_06.type = integer
salt_06.default = 51

salt_07.type = integer
salt_07.default = 11

salt_08.type = integer
salt_08.default = 228

rounds.type = integer
rounds.default = 200

